Repository ormcamp-fe-3rd/drone-go, pull requests merged in 2025-02, with the labels that each got.

#43 [반재영] 로그인 인증 오류 수정
  frontend/src/App.tsx
  frontend/src/api/dropdownApi.ts
  frontend/src/components/home/DataList.tsx
  frontend/src/components/home/LoginForm.tsx
  frontend/src/contexts/AuthContext.tsx
  frontend/src/contexts/AuthProvider.tsx
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/routes/pages/HomePage.tsx
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/src/routes/pages/MapPage.tsx
  frontend/src/types/latLonAlt.ts
Labels: ⚠️ bug

#45 [김도연] 고도&속도 차트 수정 및 엑셀 export 기능 구현
  frontend/public/images/chart/M1_1호기.svg
  frontend/public/images/chart/M1_2호기.svg
  frontend/public/images/chart/M1_3호기.svg
  frontend/src/api/chartApi.ts
  frontend/src/components/charts/AltAndSpeedChart.tsx
  frontend/src/components/charts/DetailedDataHeader.tsx
  frontend/src/components/charts/ExportToExcel.tsx
  frontend/src/routes/pages/ChartPage.tsx
Labels: 🔑 feature

#44 [반재영] 토큰 인증 에러 처리 수정
  backend/routes/userRoutes.js
  frontend/src/api/chartApi.ts
  frontend/src/api/dropdownApi.ts
  frontend/src/api/mapApi.ts
  frontend/src/api/mapToolbarApi.ts
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/src/routes/pages/MapPage.tsx
Labels: 🚧 invalid

#52 [반재영] 미니맵 위젯 마커 수정
  frontend/src/components/map3d/MiniMap.tsx
Labels: ❇️ enhancement, 🔑 feature

#51 [반재영] 로그인 전 화면 레이아웃 수정
  frontend/public/images/droneCardList.png
  frontend/src/components/home/HomeHeader.tsx
  frontend/src/components/home/LoginForm.tsx
  frontend/src/components/home/LoginModal.tsx
  frontend/src/components/home/UnloggedDroneList.tsx
  frontend/src/routes/pages/HomePage.tsx
Labels: ❇️ enhancement, 🎨 layout

#49 [반재영] 3d 지도 재생버튼 수정, selected data context 추가
  backend/app.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/stopBtn.svg
  frontend/src/App.tsx
  frontend/src/api/chartApi.ts
  frontend/src/api/mapApi.ts
  frontend/src/api/mapToolbarApi.ts
  frontend/src/components/charts/DetailedDataHeader.tsx
  frontend/src/components/map/Map2D.tsx
  frontend/src/components/map/ProgressBar.tsx
  frontend/src/components/map/ProgressBarBtn.tsx
  frontend/src/components/map/ProgressBarBtns.tsx
  frontend/src/components/map3d/CesiumViewer3D.tsx
  frontend/src/components/map3d/Map3D.tsx
  frontend/src/components/map3d/MapSwitchButton.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/constants.ts
  frontend/src/contexts/SelectedDataContext.tsx
  frontend/src/contexts/SelectedDataContextProvider.tsx
  frontend/src/hooks/useTelemetry2D.ts
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/src/routes/pages/MapPage.tsx
  frontend/src/types/operationAndDate.ts
Labels: 🧑‍💻 mentor review, 🔑 feature

#50 [김혜빈] 드론 자세변화 위젯
  frontend/src/components/map3d/AttitudeWidget.tsx
  frontend/src/components/map3d/WeatherWidget.tsx
  frontend/src/routes/pages/MapPage.tsx
Labels: 🧑‍💻 mentor review, 🔑 feature

#58 [김혜빈] 홈화면 드론 새로고침 오류 / 드론 이미지 연결
  frontend/index.html
  frontend/src/components/home/DataList.tsx
  frontend/src/components/home/Drone.tsx
  frontend/src/components/home/HeroSection.tsx
  frontend/src/components/home/UnloggedDroneList.tsx
  frontend/src/routes/pages/HomePage.tsx
Labels: ⚠️ bug

#59 [반재영] 지도 로딩화면, 안내문구 추가, 2d 맵 수정
  frontend/public/icons/to2d.svg
  frontend/public/icons/to3d.svg
  frontend/src/components/charts/DetailedDataHeader.tsx
  frontend/src/components/charts/HeaderChartBtns.tsx
  frontend/src/components/charts/HeaderMapBtns.tsx
  frontend/src/components/map/Map2D.tsx
  frontend/src/components/map/PlayHead.tsx
  frontend/src/components/map/ProgressBar.tsx
  frontend/src/components/map3d/AttitudeWidget.tsx
  frontend/src/components/map3d/CesiumViewer3D.tsx
  frontend/src/components/map3d/LoadingMessage.tsx
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/routes/pages/Map3dPage.tsx
Labels: ❇️ enhancement, 🚧 invalid, 🔑 feature

#62 [반재영] 지도 오류 수정, 드론 기본 회전값 지정, 레이아웃 수정
  frontend/src/components/charts/DetailedDataHeader.tsx
  frontend/src/components/charts/DropdownSection.tsx
  frontend/src/components/map/Map2D.tsx
  frontend/src/components/map/ProgressBar.tsx
  frontend/src/components/map3d/AttitudeWidget.tsx
  frontend/src/components/map3d/CesiumViewer3D.tsx
  frontend/src/components/map3d/LoadingMessage.tsx
  frontend/src/components/map3d/MiniMap.tsx
  frontend/src/components/map3d/WeatherWidget.tsx
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/vite.config.ts
Labels: ❇️ enhancement, 🚧 invalid, 🎨 layout

#65 [김혜빈] about resetScrollBtn 구현
  frontend/src/components/about/ResetScrollBtn.tsx
  frontend/src/routes/pages/AboutPage.tsx
  frontend/src/routes/pages/Map3dPage.tsx
Labels: 🔑 feature

#69 [반재영] 지도 세부 기능 조정
  frontend/public/images/home/droneCardList.png
  frontend/src/components/home/UnloggedDroneList.tsx
  frontend/src/components/map/Map2D.tsx
  frontend/src/components/map/ProgressBarBtns.tsx
  frontend/src/components/map3d/StateWidget.tsx
Labels: 🚧 invalid, 🔑 feature

#70 날씨 위젯 수정 반영
  frontend/src/api/fetchWeatherData.ts
  frontend/src/api/nasaApiClient.ts
  frontend/src/components/map3d/AltitudeWidget.tsx
  frontend/src/components/map3d/AttitudeWidget.tsx
  frontend/src/components/map3d/CesiumViewer3D.tsx
  frontend/src/components/map3d/MiniMapWidget.tsx
  frontend/src/components/map3d/SpeedWidget.tsx
  frontend/src/components/map3d/StateWidget.tsx
  frontend/src/components/map3d/WeatherWidget.tsx
  frontend/src/routes/pages/Map3dPage.tsx
Labels: 🚧 invalid, 🔑 feature

#73 [반재영] 드론 자세변화위젯 축 및 orbitcontrols 추가
  frontend/src/components/home/Drone.tsx
  frontend/src/components/home/HeroSection.tsx
  frontend/src/components/home/HomeHeader.tsx
  frontend/src/components/home/ListDrone.tsx
  frontend/src/components/map3d/AttitudeWidget.tsx
Labels: 🚧 invalid, 🔑 feature

#72 [반재영] 3d 지도 드론 자세변화 추가 및 카메라 수정, 2d 지도 마커 수정
  frontend/public/images/map/droneMarker.svg
  frontend/src/components/map/Map2D.tsx
  frontend/src/components/map3d/CesiumViewer3D.tsx
  frontend/src/hooks/useAnimationTime.tsx
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/src/utils/addMapSourceLayerMarker.ts
  frontend/src/utils/initCesiumMap.ts
  frontend/src/utils/updateDronePosition.ts
Labels: ❇️ enhancement, ⚒️ refactoring, 🔑 feature

#74 최종 피드백 반영
  frontend/public/fonts/Pretendard-Black.ttf
  frontend/public/fonts/Pretendard-Black.woff2
  frontend/public/fonts/Pretendard-Bold.ttf
  frontend/public/fonts/Pretendard-Bold.woff2
  frontend/public/fonts/Pretendard-ExtraBold.ttf
  frontend/public/fonts/Pretendard-ExtraBold.woff2
  frontend/public/fonts/Pretendard-ExtraLight.ttf
  frontend/public/fonts/Pretendard-ExtraLight.woff2
  frontend/public/fonts/Pretendard-Light.ttf
  frontend/public/fonts/Pretendard-Light.woff2
  frontend/public/fonts/Pretendard-Medium.ttf
  frontend/public/fonts/Pretendard-Medium.woff2
  frontend/public/fonts/Pretendard-Regular.ttf
  frontend/public/fonts/Pretendard-Regular.woff2
  frontend/public/fonts/Pretendard-SemiBold.ttf
  frontend/public/fonts/Pretendard-SemiBold.woff2
  frontend/public/images/map/droneMarker.svg
  frontend/src/components/home/Drone.tsx
  frontend/src/components/home/HeroSection.tsx
  frontend/src/components/home/HomeHeader.tsx
  frontend/src/components/home/ListDrone.tsx
  frontend/src/components/map/Map2D.tsx
  frontend/src/components/map3d/AttitudeWidget.tsx
  frontend/src/components/map3d/CesiumViewer3D.tsx
  frontend/src/hooks/useAnimationTime.tsx
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/src/styles/input.css
  frontend/src/utils/addMapSourceLayerMarker.ts
  frontend/src/utils/initCesiumMap.ts
  frontend/src/utils/updateDronePosition.ts
Labels: ❇️ enhancement, ⚒️ refactoring
