Repository ormcamp-fe-3rd/drone-go, pull requests merged in 2025-01, with the labels that each got.

#7 [김도연] 차트 페이지 레이아웃
  frontend/components.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icons/ListPage.png
  frontend/public/icons/download.png
  frontend/public/icons/maps.png
  frontend/public/icons/setting-error.png
  frontend/public/icons/time.png
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/lib/utils.ts
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/ChartPage.tsx
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
Labels: 🎨 layout

#8 [김혜빈] fix: merge conflict
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.tsx
  frontend/tailwind.config.js
Labels: ⚠️ bug

#9 [반재영] 소개페이지 레이아웃 구현
  frontend/public/images/introduce/drone.png
  frontend/public/images/introduce/section01-chart-01.png
  frontend/public/images/introduce/section01-chart-02.png
  frontend/public/images/introduce/section01-chart-bg.png
  frontend/public/images/introduce/section01-map-01.png
  frontend/public/images/introduce/section01-map-02.png
  frontend/public/images/introduce/section01-map-03.png
  frontend/public/images/introduce/section01-map-bg.png
  frontend/public/images/introduce/section02-chart.png
  frontend/public/images/introduce/section02-main.png
  frontend/public/images/introduce/section02-map.png
  frontend/public/images/introduce/section03-01.png
  frontend/public/images/introduce/section03-02.png
  frontend/public/images/introduce/section03-03.png
  frontend/public/images/introduce/section03-04.png
  frontend/src/App.tsx
  frontend/src/components/about/FunctionSection.tsx
  frontend/src/components/about/MemberCard.tsx
  frontend/src/components/about/TeamSection.tsx
  frontend/src/components/about/UsecaseCard.tsx
  frontend/src/components/about/UsecaseSection.tsx
  frontend/src/components/about/WelcomeSection.tsx
  frontend/src/components/main/Header.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/AboutPage.tsx
  frontend/src/routes/pages/HomePage.tsx
  frontend/src/routes/pages/IntroducePage.tsx
Labels: 👯 team review, 🧑‍💻 mentor review, 🎨 layout

#12 [김도연] ChartPage 상단 부분 컴포넌트화
  backend/app.js
  backend/controllers/operationController.js
  backend/controllers/telemetryController.js
  backend/package-lock.json
  backend/package.json
  backend/routes/index.js
  backend/routes/operationRoutes.js
  backend/routes/telemetryRoutes.js
  backend/services/operationService.js
  backend/services/telemetryService.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icons/ListPage.png
  frontend/public/icons/Vector.svg
  frontend/public/icons/charts.svg
  frontend/public/icons/download.png
  frontend/public/icons/download.svg
  frontend/public/icons/maps.png
  frontend/public/icons/maps.svg
  frontend/public/icons/setting-error.png
  frontend/public/icons/setting-error.svg
  frontend/public/icons/time.png
  frontend/public/icons/time.svg
  frontend/src/api/chartApi.ts
  frontend/src/api/dropdownApi.ts
  frontend/src/components/charts/BatteryChartData.tsx
  frontend/src/components/charts/DetailedDataHeader.tsx
  frontend/src/components/charts/DropdownComponent.tsx
  frontend/src/components/charts/DropdownSection.tsx
  frontend/src/main.tsx
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/types/selectOptionsTypes.ts
  frontend/src/types/telemetryBatteryDataTypes.ts
Labels: 🧑‍💻 mentor review, 🎨 layout, 🔑 feature

#20 [김혜빈] 메인 버튼 추가 및 스크롤 컴포먼트 추가, 카드 컴포먼트 수정
  frontend/public/images/drone-01.svg
  frontend/public/images/drone-02.svg
  frontend/src/components/home/DataList.tsx
  frontend/src/components/home/FlightDataCard.tsx
  frontend/src/components/home/HeroSection.tsx
  frontend/src/components/home/HomeHeader.tsx
  frontend/src/hooks/scroollToTop.tsx
  frontend/src/routes/index.tsx
Labels: 🎨 layout

#18 [반재영] 3d 지도 생성, 드론 추가
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icons/loading.svg
  frontend/public/icons/to-2dmap.svg
  frontend/public/icons/to-3dmap.svg
  frontend/public/icons/vite.svg
  frontend/public/images/vite.svg
  frontend/src/api/mapApi.ts
  frontend/src/components/charts/DetailedDataHeader.tsx
  frontend/src/components/map/ToolbarAttitude.tsx
  frontend/src/components/map3d/DroneInMap.tsx
  frontend/src/components/map3d/Map3D.tsx
  frontend/src/components/map3d/MapSwitchButton.tsx
  frontend/src/components/map3d/Widget.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/src/routes/pages/MapPage.tsx
  frontend/src/types/telemetryPositionDataTypes.ts
  frontend/src/types/widgetDataTypes.ts
Labels: 🚧 invalid, 👯 team review, 🔑 feature

#22 [김도연]state데이터 컴포넌트 추가, 드론 이미지, 드론 연결 위성 수 데이터 차트 컴포넌트 추가
  frontend/public/images/chart/drone1.svg
  frontend/public/images/chart/drone2.svg
  frontend/src/api/chartApi.ts
  frontend/src/components/charts/BatteryChart.tsx
  frontend/src/components/charts/DetailedDataHeader.tsx
  frontend/src/components/charts/FilghtTimeDataComponent.tsx
  frontend/src/components/charts/SatellitesChart.tsx
  frontend/src/components/charts/StateDataComponent.tsx
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/types/telemetryAllDataTypes.ts
  frontend/src/types/telemetryBatteryDataTypes.ts
  frontend/src/types/telemetrySatellitesDataTypes.ts
  frontend/src/types/telemetryTextData.ts
  frontend/src/utils/formatTime.ts
Labels: 🔑 feature

#23 [반재영] 3d 지도 이동 애니메이션 , 위도, 경도 데이터 연결
  frontend/public/images/pause.svg
  frontend/src/api/mapApi.ts
  frontend/src/components/map/ProgressBar.tsx
  frontend/src/components/map3d/Map3D.tsx
  frontend/src/components/map3d/Widget.tsx
  frontend/src/data/latLonDataCamera.json
  frontend/src/data/latLonDataTarget.json
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/src/types/latLonAlt.ts
  frontend/src/types/telemetryPositionDataTypes.ts
  frontend/src/utils/calculateDistance.ts
  frontend/src/utils/formatPositionData.ts
Labels: 🚧 invalid, 🧑‍💻 mentor review, 🔑 feature

#25 [김혜빈] Layout main feedback
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/home/DataList.tsx
  frontend/src/components/home/FlightDataCard.tsx
  frontend/src/components/home/HeroSection.tsx
  frontend/src/hooks/scroollToTop.tsx
  frontend/src/hooks/useScrollReset.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/HomePage.tsx
Labels: 🎨 layout

#28 [김도연] 차트 툴팁 수정
  frontend/src/components/charts/BatteryChart.tsx
  frontend/src/components/charts/SatellitesChart.tsx
Labels: 🔑 feature

#24 [김수진]지도-2d 레이아웃 수정 및 나침반 데이터 요청
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/Group 906.svg
  frontend/src/App.tsx
  frontend/src/api/mapToolbarApi.ts
  frontend/src/cesiumConfig.ts
  frontend/src/components/map/AttitudeViewer.tsx
  frontend/src/components/map/CesiumViewer.tsx
  frontend/src/components/map/Map2D.tsx
  frontend/src/components/map/ProgressBar.tsx
  frontend/src/components/map/ToolbarAttitude.tsx
  frontend/src/components/map/ToolbarWidget.tsx
  frontend/src/components/map3d/Widget.tsx
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/src/routes/pages/MapPage.tsx
  frontend/src/styles/input.css
  frontend/src/types/telemetryAllDataTypes.ts
  frontend/src/types/telemetryAttitudeDataTypes.ts
  frontend/src/utils/calculateDistance.ts
Labels: 🧑‍💻 mentor review, 🔑 feature

#38 [김혜빈] main drone list data state -> chart page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/dropdownApi.ts
  frontend/src/components/home/DataList.tsx
  frontend/src/components/home/FlightDataCard.tsx
  frontend/src/components/home/HomeHeader.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/routes/pages/HomePage.tsx
Labels: 🔑 feature

#41 [김도연]드롭다운 컴포넌트 수정
  frontend/src/api/chartApi.ts
  frontend/src/api/dropdownApi.ts
  frontend/src/components/charts/BatteryChart.tsx
  frontend/src/components/charts/DetailedDataHeader.tsx
  frontend/src/components/charts/DropdownComponent.tsx
  frontend/src/components/charts/DropdownSection.tsx
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/types/altAndspeedDataType.ts
  frontend/src/types/telemetryAllDataTypes.ts
Labels: 🔑 feature

#37 [반재영] 로그인 기능 구현
  backend/middleware/authorizer.js
  backend/package-lock.json
  backend/package.json
  backend/routes/index.js
  backend/routes/operationRoutes.js
  backend/routes/robotRoutes.js
  backend/routes/telemetryRoutes.js
  backend/routes/userRoutes.js
  frontend/src/App.tsx
  frontend/src/api/chartApi.ts
  frontend/src/api/dropdownApi.ts
  frontend/src/api/mapApi.ts
  frontend/src/api/mapToolbarApi.ts
  frontend/src/api/userApi.ts
  frontend/src/components/home/HomeHeader.tsx
  frontend/src/components/home/LoginForm.tsx
  frontend/src/components/home/LoginModal.tsx
  frontend/src/contexts/AuthContext.tsx
  frontend/src/contexts/UserContext.tsx
  frontend/src/routes/pages/ChartPage.tsx
  frontend/src/routes/pages/HomePage.tsx
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/src/routes/pages/MapPage.tsx
Labels: 🧑‍💻 mentor review, 🔑 feature

#32 [반재영] 3d 지도 애니메이션 수정, 재생바 기능 구현, 미니맵 추가
  frontend/public/icons/playHead.svg
  frontend/src/api/mapApi.ts
  frontend/src/components/map/Map2D.tsx
  frontend/src/components/map/PlayHead.tsx
  frontend/src/components/map/ProgressBar.tsx
  frontend/src/components/map/ProgressBarBtn.tsx
  frontend/src/components/map3d/AltitudeWidget.tsx
  frontend/src/components/map3d/AttitudeWidget.tsx
  frontend/src/components/map3d/DroneInMap.tsx
  frontend/src/components/map3d/Map3D.tsx
  frontend/src/components/map3d/MiniMap.tsx
  frontend/src/components/map3d/MiniMapWidget.tsx
  frontend/src/components/map3d/SpeedWidget.tsx
  frontend/src/components/map3d/StateWidget.tsx
  frontend/src/components/map3d/WeatherWidget.tsx
  frontend/src/contexts/PhaseContext.tsx
  frontend/src/routes/pages/Map3dPage.tsx
  frontend/src/routes/pages/MapPage.tsx
  frontend/src/types/telemetryPositionDataTypes.ts
  frontend/src/utils/calculateDistance.ts
  frontend/src/utils/formatNumberTime.ts
  frontend/src/utils/formatPositionData.ts
  frontend/src/utils/formatTime.ts
Labels: 🧑‍💻 mentor review, 🔑 feature
